baseURL = 'https://lucidmechanisms.netlify.app/'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

staticDir = ["static", "themes/Niello/static"]

theme = "niello"

[params]
    copyright = "&#xA9; 2024 by Tehoor Marjan. CC0."

[outputs]
    home = ["HTML", "JSON"]

[languages]
    [languages.en]
        title = "Lucid Mechanisms"
        languageCode = "en-us"
        LanguageName = "🇺🇸EN"
        contentDir = "content/en"
        weight = 0
        [languages.en.permalinks]
            [languages.en.permalinks.page]
                posts = "posts/:year/:month/:slug"
        [[languages.en.menus.main]]
            name = 'Home'
            pageRef = '/'
            weight = 1
        [[languages.en.menus.main]]
            name = 'Me'
            pageRef = '/me'
            weight = 2

    [languages.fr]
        title = "Lucid Mechanisms"
        languageCode = "fr-FR"
        LanguageName = "🇫🇷FR"
        contentDir = "content/fr"
        weight = 1
        [languages.fr.permalinks]
            [languages.fr.permalinks.page]
                posts = "articles/:year/:month/:slug"
        [[languages.fr.menus.main]]
            name = 'Accueil'
            pageRef = '/'
            weight = 1
        [[languages.fr.menus.main]]
            name = 'Moi'
            pageRef = '/me'
            weight = 2
