[build.environment]
HUGO_VERSION = "0.139.3"
GO_VERSION = "1.23.4"

[context.production]
publish = "public"
command = "yarn build"

[context.deploy-preview]
publish = "public"
command = "yarn build -- -b ${DEPLOY_URL}"
