name = "Lucidpearl"
license = "MIT"
licenselink = "https://github.com/TehoorMarjan/lucidmechanisms/tree/main/themes/lucidpearl/LICENSE"
description = "Lucidpearl is a theme for Lucid Mechanisms."
homepage = "https://lucidmechanisms.netlify.app/"
demosite = "https://lucidmechanisms.netlify.app/"
min_version = "0.139.3"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Multi-Authors",
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Tehoor Marjan"
homepage = "https://lucidmechanisms.netlify.app/"

[original]
author = "Zeon Studio"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
